# Lesson

title:
handouts:
tag:
lesson:
instructor:
authors:

title: "Unstructured and Qualitative Data"
handouts: worksheet.R
tag: v0.0
instructor: Ian Carroll
authors:
 - Ian Carroll
lesson: 8

# Slides

slide_sorter:
  - data
  - scraping
  - mining
  - content
  - topic
  - conclude

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/1.1/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0

# Jekyll

markdown: kramdown
collections:
  - slides
