# Site

title: "Extracting and Mining Texts for Structured Data"
handouts:
 - worksheet.R
 - data/enron
 - data/README.md
tag: v0.1
instructor: Ian Carroll
authors:
 - Ian Carroll
lesson: 8

# Slides

slide_sorter:
  - data
  - scraping
  - networks
  - mining
  - content
#  - topic
#  - qual

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
